// This file is automatically generated and contains assets from celo.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssetAggregators: Address[][];
}

export const cUSD_ADDRESS = Address.fromString('0x765de816845861e75a25fca122bb6898b8b1282a');
export const USDC_ADDRESS = Address.fromString('0x765de816845861e75a25fca122bb6898b8b1282a');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x765de816845861e75a25fca122bb6898b8b1282a'), // cUSD
    Address.fromString('0x765de816845861e75a25fca122bb6898b8b1282a'), // USDC
  ],
  pricingAssets: [
    Address.fromString('0x471EcE3750Da237f93B8E339c536989b8978a438'), // CELO
    Address.fromString('0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73'), // cEUR
    Address.fromString('0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787'), // cREAL
  ],
  fxAssetAggregators: [],
};
